name: letamind
description: A word game; guess the hidden word.
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/letamind/
issue_tracker: https://github.com/bennorichters/letamind/issues
homepage: https://bennorichters.github.io/letamind/

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/lang/en/
    - assets/lang/hu/
    - assets/lang/nl/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "scripts/images/logo.png"

flutter_native_splash:
  color: "F5DEB3"
